export const colors = {
  bgPrimary: '#FFFFFF',
  bgSecondary: '#F5F5F5',
  bgTertiary: '#EFEFEF',
  darkSurface: '#0A0A0A',
  darkSurfaceSecondary: '#1A1A1A',
  darkSurfaceTertiary: '#2A2A2A',
  textPrimary: '#0A0A0A',
  textSecondary: '#6B6B6B',
  textTertiary: '#9B9B9B',
  textInverted: '#FFFFFF',
  border: '#E5E5E5',
  borderDark: '#2A2A2A',
  accent: '#0A0A0A',
  success: '#16A34A',
  error: '#DC2626',
  warning: '#D97706',
  statusClient: '#16A34A',
  statusProspect: '#6B6B6B',
} as const
